// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using SavingsOnDapr.Dashboard.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\currency-exchange-summary\{source}\{target}\{forDate}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithForDateItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithForDateItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/currency-exchange-summary/{source}/{target}/{forDate}{?toDate*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithForDateItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/currency-exchange-summary/{source}/{target}/{forDate}{?toDate*}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryResponse?> GetAsync(Action<RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryResponse> GetAsync(Action<RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryResponse>(requestInfo, global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(Action<RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(Action<RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class WithForDateItemRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("toDate")]
            public DateTimeOffset? ToDate { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithForDateItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderGetQueryParameters>
        {
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class WithForDateItemRequestBuilderPostQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("toDate")]
            public DateTimeOffset? ToDate { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithForDateItemRequestBuilderPostRequestConfiguration : RequestConfiguration<global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder.WithForDateItemRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
