// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SavingsOnDapr.Dashboard.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AccountType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SavingsAccount")]
        #pragma warning disable CS1591
        SavingsAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "CurrentAccount")]
        #pragma warning disable CS1591
        CurrentAccount,
        #pragma warning restore CS1591
    }
}
