// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SavingsOnDapr.Dashboard.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateCurrentAccount : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountCurrency property</summary>
        public global::SavingsOnDapr.Dashboard.Client.Models.Currency? AccountCurrency { get; set; }
        /// <summary>The externalRef property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalRef { get; set; }
#nullable restore
#else
        public string ExternalRef { get; set; }
#endif
        /// <summary>The userId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SavingsOnDapr.Dashboard.Client.Models.CreateCurrentAccount"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SavingsOnDapr.Dashboard.Client.Models.CreateCurrentAccount CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SavingsOnDapr.Dashboard.Client.Models.CreateCurrentAccount();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountCurrency", n => { AccountCurrency = n.GetEnumValue<global::SavingsOnDapr.Dashboard.Client.Models.Currency>(); } },
                { "externalRef", n => { ExternalRef = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::SavingsOnDapr.Dashboard.Client.Models.Currency>("accountCurrency", AccountCurrency);
            writer.WriteStringValue("externalRef", ExternalRef);
            writer.WriteStringValue("userId", UserId);
        }
    }
}
#pragma warning restore CS0618
