// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SavingsOnDapr.Dashboard.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Currency
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "EUR")]
        #pragma warning disable CS1591
        EUR,
        #pragma warning restore CS1591
        [EnumMember(Value = "USD")]
        #pragma warning disable CS1591
        USD,
        #pragma warning restore CS1591
        [EnumMember(Value = "GBP")]
        #pragma warning disable CS1591
        GBP,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHF")]
        #pragma warning disable CS1591
        CHF,
        #pragma warning restore CS1591
        [EnumMember(Value = "PLN")]
        #pragma warning disable CS1591
        PLN,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOK")]
        #pragma warning disable CS1591
        NOK,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAD")]
        #pragma warning disable CS1591
        CAD,
        #pragma warning restore CS1591
    }
}
