// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SavingsOnDapr.Dashboard.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CurrencyExchangeSummaryResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The columnNames property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ColumnNames { get; set; }
#nullable restore
#else
        public List<string> ColumnNames { get; set; }
#endif
        /// <summary>The entries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryValueEntry>? Entries { get; set; }
#nullable restore
#else
        public List<global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryValueEntry> Entries { get; set; }
#endif
        /// <summary>The responseKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResponseKey { get; set; }
#nullable restore
#else
        public string ResponseKey { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "columnNames", n => { ColumnNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "entries", n => { Entries = n.GetCollectionOfObjectValues<global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryValueEntry>(global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryValueEntry.CreateFromDiscriminatorValue)?.AsList(); } },
                { "responseKey", n => { ResponseKey = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("columnNames", ColumnNames);
            writer.WriteCollectionOfObjectValues<global::SavingsOnDapr.Dashboard.Client.Models.CurrencyExchangeSummaryValueEntry>("entries", Entries);
            writer.WriteStringValue("responseKey", ResponseKey);
        }
    }
}
#pragma warning restore CS0618
