// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SavingsOnDapr.Dashboard.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CurrencyRateResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountCurrency property</summary>
        public global::SavingsOnDapr.Dashboard.Client.Models.Currency? AccountCurrency { get; set; }
        /// <summary>The interestRate property</summary>
        public double? InterestRate { get; set; }
        /// <summary>The timestamp property</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SavingsOnDapr.Dashboard.Client.Models.CurrencyRateResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SavingsOnDapr.Dashboard.Client.Models.CurrencyRateResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::SavingsOnDapr.Dashboard.Client.Models.CurrencyRateResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountCurrency", n => { AccountCurrency = n.GetEnumValue<global::SavingsOnDapr.Dashboard.Client.Models.Currency>(); } },
                { "interestRate", n => { InterestRate = n.GetDoubleValue(); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::SavingsOnDapr.Dashboard.Client.Models.Currency>("accountCurrency", AccountCurrency);
            writer.WriteDoubleValue("interestRate", InterestRate);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
        }
    }
}
#pragma warning restore CS0618
