// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace SavingsOnDapr.Dashboard.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ExchangeOrderType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "GuaranteedRate")]
        #pragma warning disable CS1591
        GuaranteedRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "MarketRate")]
        #pragma warning disable CS1591
        MarketRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "LimitOrder")]
        #pragma warning disable CS1591
        LimitOrder,
        #pragma warning restore CS1591
    }
}
