// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SavingsOnDapr.Dashboard.Client.Api.Savings.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SavingsOnDapr.Dashboard.Client.Api.Savings
{
    /// <summary>
    /// Builds and executes requests for operations under \api\savings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SavingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the SavingsOnDapr.Dashboard.Client.api.savings.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::SavingsOnDapr.Dashboard.Client.Api.Savings.Item.WithCurrencyItemRequestBuilder"/></returns>
        public global::SavingsOnDapr.Dashboard.Client.Api.Savings.Item.WithCurrencyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("currency", position);
                return new global::SavingsOnDapr.Dashboard.Client.Api.Savings.Item.WithCurrencyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SavingsOnDapr.Dashboard.Client.Api.Savings.SavingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SavingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/savings", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SavingsOnDapr.Dashboard.Client.Api.Savings.SavingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SavingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/savings", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
