// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SavingsOnDapr.Dashboard.Client.Api.Currency.ExchangeOrder;
using SavingsOnDapr.Dashboard.Client.Api.Currency.ExchangeQuery;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SavingsOnDapr.Dashboard.Client.Api.Currency
{
    /// <summary>
    /// Builds and executes requests for operations under \api\currency
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CurrencyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The exchangeOrder property</summary>
        public global::SavingsOnDapr.Dashboard.Client.Api.Currency.ExchangeOrder.ExchangeOrderRequestBuilder ExchangeOrder
        {
            get => new global::SavingsOnDapr.Dashboard.Client.Api.Currency.ExchangeOrder.ExchangeOrderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exchangeQuery property</summary>
        public global::SavingsOnDapr.Dashboard.Client.Api.Currency.ExchangeQuery.ExchangeQueryRequestBuilder ExchangeQuery
        {
            get => new global::SavingsOnDapr.Dashboard.Client.Api.Currency.ExchangeQuery.ExchangeQueryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SavingsOnDapr.Dashboard.Client.Api.Currency.CurrencyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrencyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/currency", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SavingsOnDapr.Dashboard.Client.Api.Currency.CurrencyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CurrencyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/currency", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
