// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\currency-exchange-summary\{source}\{target}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTargetItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the SavingsOnDapr.Dashboard.Client.api.currencyExchangeSummary.item.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder"/></returns>
        public global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder this[DateTimeOffset position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("forDate", position);
                return new global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the SavingsOnDapr.Dashboard.Client.api.currencyExchangeSummary.item.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("forDate", position);
                return new global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.Item.WithForDateItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.WithTargetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTargetItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/currency-exchange-summary/{source}/{target}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SavingsOnDapr.Dashboard.Client.Api.CurrencyExchangeSummary.Item.Item.WithTargetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTargetItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/currency-exchange-summary/{source}/{target}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
